CREATE SCHEMA IF NOT EXISTS dominio;
CREATE SCHEMA IF NOT EXISTS seguranca;
CREATE SCHEMA IF NOT EXISTS auditoria;

CREATE TABLE IF NOT EXISTS seguranca.usuario
(
    seq_usuario integer generated by default as identity,
    username    varchar(30) not null unique,
    senha       varchar(60),
    primary key (seq_usuario)
);

CREATE TABLE IF NOT EXISTS dominio.produtor
(
    id   integer generated by default as identity,
    nome varchar(60) not null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS dominio.album
(
    id          integer generated by default as identity,
    autor       varchar(60) not null,
    titulo      varchar(80) not null,
    produtor_id integer     not null,
    primary key (id),
    CONSTRAINT fk_album_produtor FOREIGN KEY (produtor_id)
        REFERENCES dominio.produtor (id)
);

CREATE TABLE IF NOT EXISTS dominio.musica
(
    id       integer generated by default as identity,
    letra    varchar(255) not null,
    titulo   varchar(60)  not null,
    album_id integer      not null,
    primary key (id),
    CONSTRAINT fk_musica_album FOREIGN KEY (album_id)
        REFERENCES dominio.album (id)
);

// INSERT's

MERGE INTO seguranca.usuario (username, senha) KEY (username)
    VALUES ('test1', '$2a$10$Xu9SeWMo8Ho.uCqII97GZObmWCnzVj.km/dS60hSBsAdLWYZ6T3iG'); // test1

MERGE INTO seguranca.usuario (username, senha) KEY (username)
    VALUES ('test2', '$2a$10$wO/HyhdWXntEpILnsojIa.w9ZLmfMC/Zlvsop1lCXc1vjeOCh2.pi'); // test2
